### ISSUE TITLE
Client JSON blob signing and Contract validation of signature.

### ISSUE THREAD

**Issue by lathanbritz** [EvernodeXRPL/hp-js-client#2]
<img width="480" alt="Screen Shot 2023-04-27 at 16 55 49" src="https://user-images.githubusercontent.com/508629/234989196-2b7666c4-1990-4029-a2e9-5e804758d0b2.png">

I would like to achieve something along the lines of the following. 
1. take a JSON object convert it to a string.
2. sign that string with the client privateKey and push it to the contract
3. on the contract now validate that the String received was signed by the publicKey that the clie
nt used.

Or is that already happening automatically via a  `client.submitContractInput(JSON.stringify(data))` ... my assumption is that nothing is encoded/decoded?

<img width="579" alt="Screen Shot 2023-04-27 at 17 00 05" src="https://user-images.githubusercontent.com/508629/234990069-06e0d3fb-cf52-423d-8b03-6eda6985bf95.png">

where in the contract anything that has been sent from the user.publicKey has already been signed?

**Comment by ravinsp** [comment]
@lathanbritz You don't really need to do this as the client/server signature verification happens at the start of establishing the websocket connection to HotPocket. So the WebSocket channel itself is already authenticated and you don't need to perform this with every message.

This is what happens:

1. Client establishes a secure web socket connection to HotPocket server.
2. HotPocket then sends a challenge to the client.
3. Client must sign the challenge and send back the signature and the public key to the server.
4. Server will verify the challenge signature with the provided public key.
5. No others messages are exchanged before this process completes. If the challenge verification fails, HotPocket will drop the connection.
6. From this point on, we know that web socket channel belongs to the party who owns the specified public key.

Additional notes:
- The inverse of the above process happens to authenticate the server to the client also. So the client knows the server is the actual owner of the provided server public key. You can enforce this with [trustedServerKeys option](https://github.com/EvernodeXRPL/hp-js-client/blob/main/example/browser-example.html#L34) in the client.
- Same process is used between HotPocket instances as well to authenticate each other.

**Comment by ravinsp** [comment]
@lathanbritz Did the above answer your concern? is there anything remaining to be clarified?

**Comment by lathanbritz** [comment]
Sorry yes thanks, on mobile here not sure how to close this please do!
