### ISSUE TITLE
How can spec a different port?

### ISSUE THREAD

**Issue by lathanbritz** [EvernodeXRPL/hp-js-client#3]
<img width="1027" alt="Screen Shot 2023-04-28 at 13 13 45" src="https://user-images.githubusercontent.com/508629/235211795-76290a09-4683-4aeb-b6a6-91c6b04dc220.png">

to overcome building on different env in evernode im just using my server atm to build and run till i can figure out how to get ncc to compile for a different target env.

but my sever has already occupied the port and i dont find any reference to adjusting the port here https://github.com/EvernodeXRPL/evernode-sdk/blob/main/hotpocket/reference-configuration.md

**Comment by wojake** [comment]
Each HotPocket instance has 1 peer port and 1 user port since a machine could only generate and use 1 IP address at a time, docker containers couldn't use an individual IP address

**Comment by lathanbritz** [comment]
Thanks @wojake Yup I saw containers get created for 8081 and 8082 but id like to be able to bump the port range around, via a config.

**Comment by ravinsp** [comment]
@lathanbritz This is possible with hpdevkit environment variables: https://github.com/EvernodeXRPL/evernode-sdk/blob/main/hpdevkit/index.md#environment-variables

**Comment by lathanbritz** [comment]
![image](https://user-images.githubusercontent.com/508629/235280942-e2022f11-48f3-401a-9c9d-1466cda7ff11.jpeg)

Thank you I missed that!
