### ISSUE TITLE
Client Side es5/6

### ISSUE THREAD

**Issue by lathanbritz** [EvernodeXRPL/hp-js-client#4]
<img width="292" alt="Screen Shot 2023-04-28 at 22 28 04" src="https://user-images.githubusercontent.com/508629/235279640-ef35f969-f223-41a8-b1d4-a0629e030952.png">
<img width="422" alt="Screen Shot 2023-04-28 at 22 32 27" src="https://user-images.githubusercontent.com/508629/235279642-dea6553f-1a17-4980-854f-88fbf7ddcbc6.png">

how to import client side lib?
<img width="1284" alt="Screen Shot 2023-04-28 at 22 27 54" src="https://user-images.githubusercontent.com/508629/235279678-3fbb85ff-1a10-4d3a-8072-462b8b119365.png">

ive tried 
`import HotPocket from 'hotpocket-js-client'`
`import {HotPocket} from 'hotpocket-js-client'`

both give the error above

the only client side example given is a pure javascript example in the browser https://github.com/EvernodeXRPL/hp-js-client/blob/main/example/client.js

**Comment by lathanbritz** [comment]
Got it working but its a little ugly to say the least.

<img width="235" alt="Screen Shot 2023-04-30 at 22 04 49" src="https://user-images.githubusercontent.com/508629/235390939-d7bfbbb7-3c13-4182-9f7a-88937dabfdf0.png">

this should be cleaned up.

**Comment by ravinsp** [comment]
@lathanbritz This is not something that we plan to focus on anytime soon. In the browser "HotPocket" is injected into the "window" global and in NodeJs it's [CommonJS module](https://nodejs.org/api/modules.html#modules-commonjs-modules).

In the browser, as the [browser example](https://github.com/EvernodeXRPL/hp-js-client/blob/main/example/browser-example.html) shows, you don't need to prefix with `window.HotPocket`. Just using `HotPocket` will automatically will refer to the global HotPocket object.

**Comment by lathanbritz** [comment]
Closing this as its working for now. But still a +1 for cleaner injection process for react/vue type frameworks.
