### ISSUE TITLE
Client side Browser example fails.

### ISSUE THREAD

**Issue by lathanbritz** [EvernodeXRPL/hp-js-client#5]
The example strait from https://github.com/EvernodeXRPL/hp-js-client/blob/main/example/browser-example.html
fails with the error 
<img width="1288" alt="Screen Shot 2023-04-29 at 12 07 06" src="https://user-images.githubusercontent.com/508629/235312291-f24125aa-6085-4877-bb69-4a34157d0e75.png">

local HP Server running on 8081 and another server side client connected to it (in pink)
<img width="1594" alt="Screen Shot 2023-04-29 at 12 07 15" src="https://user-images.githubusercontent.com/508629/235312294-58bff9ba-9d52-434a-9ae2-f9bffa2d2a98.png">

**Comment by lathanbritz** [comment]
my guess here is that im connecting to the docker hp dev instance and it has no certificate... my guess is that the hp-js-client should not be looking for a certificate when connecting to localhost / 127.0.0.1

**Comment by ravinsp** [comment]
@lathanbritz In browsers, there's no way to bypass this using code (only solution is to manually add an exception website to the browser settings manually). Here's how to do this:
1. In your browser visit the url: https://localhost:8081 (not wss://, you need to use https:// here)
2. Browser will complain about invalid certificate but there should be a button to allow this website.
3. After adding the bypass rule in browser, your browser client will start working.

This is exactly why we also required Evernode hosts to have proper domain names when registering.

**Comment by ravinsp** [comment]
@lathanbritz The steps for bypassing the SSL certificate error in your browser for HotPocket should be the same as how you would do this to get your browser connected to any local app that is using a self-signed cert.
If possible, you can try with running a simple development web server with a self signed certificate and try to get your browser connect to that web server and display web pages from it.

Are you using Mac Safari browser. Saw [this](https://derflounder.wordpress.com/2020/04/19/enabling-safari-to-successfully-connect-after-changing-a-self-signed-certificate/) when googling. Not sure if it works but there are few cumbersome steps.

**Comment by lathanbritz** [comment]
Finally got it working after a lot of fiddling adding this to a client should not be so difficult. Last request here on this is there a way to add this certificate to the hpdevkit instance? As i need a publicly exposed dev instance anyhow.

How do i go about adding a SSL cert to the dev instance? does that need to be something done in hpdevkit for this? Or can I reveerse proxy and simply add a certificate via caddy for this.

**Comment by lathanbritz** [comment]
<img width="731" alt="Screen Shot 2023-05-03 at 21 50 31" src="https://user-images.githubusercontent.com/508629/236091971-ccdc55d6-5f4c-4f8c-8c44-9ba8d060a36e.png">
I had a go and added the caddy reverse proxy, like i do for a xrpl node. Where by caddy is the one adding the cert, but looks like hotpocket does not like it in the middle with the cert it provides... looks like this cert will have to come from the hpdevkit

**Comment by ravinsp** [comment]
@lathanbritz version 0.5.5 has been published which addresses the syntax issue you faced (and some other syntax improvements).

You can access the updated browser library via:
https://cdn.jsdelivr.net/npm/hotpocket-js-client@0.5.5/browser.min.js

I will get back to you on other SSL certificate issues/ideas you've mentioned.

**Comment by ravinsp** [comment]
@lathanbritz Regarding caddy, as I understand, it will serve HTTPS traffic using the cert you provide to caddy. Here are couple of points you need to consider:
  1. Caddy needs to proxy websocket traffic (not just HTTP web pages). Make sure you have added relevant Caddy configurations to support that. (ont sure whether [this](https://caddy.community/t/caddy-v2-how-to-proxy-websoket-v2ray-websocket-tls/7040) will help?)
  2. The connection between Caddy and HotPocket still needs to use TLS. Normally in reverse proxy it is assumed backend server is non-secure (HTTP).

I think using a reverse proxy is the best solution as hpdevkit is only intended for local development. Nevertheless, I could provide you some instructions on how to copy your own certificates into the hpdevkit HotPocket nodes (this might be messy). Let me know if Caddy doesn't work we can try the hpdevkit.

We could provide the ability to specify your own certs to hpdevkit more easily in the future.

**Comment by lathanbritz** [comment]
do you know off hand what headers it looking for? i tried appending those which you linked to in that issue but that seems not to be everything its looking for.

```
{
    header_up Host {host}
    header_up X-Real-IP {remote_host}
    header_up X-Forwarded-For {remote_host}
    header_up X-Forwarded-Proto {scheme}
}
```

**Comment by lathanbritz** [comment]
yay figured it out :)


```
evernode-client.somdomain.com:443 {
        reverse_proxy xx.xx.xx.xx:8082 {
                transport http {
                        tls
                        tls_insecure_skip_verify
                }
        }
}
```

stripped my details
but here the config that works, as ws -> wss is automatic in caddy v2 its the http -> https transport that is needed for some part of this handshake.
